# Generated by Django 6.0.1 on 2026-02-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraccounts_followers_useraccounts_following'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='useraccounts',
            new_name='CustomUser',
        ),
    ]
