# Generated by Django 6.0.1 on 2026-02-07 20:36

import relationship_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', relationship_app.models.CustomUserManager()),
            ],
        ),
    ]
